/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace VoteGuardNational {
  export type CandidateStruct = {
    name: string;
    party: string;
    voteCount: BigNumberish;
    active: boolean;
  };

  export type CandidateStructOutput = [
    name: string,
    party: string,
    voteCount: bigint,
    active: boolean
  ] & { name: string; party: string; voteCount: bigint; active: boolean };
}

export interface VoteGuardNationalInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "CANDIDATE_ADMIN_ROLE"
      | "DEFAULT_ADMIN_ROLE"
      | "VERIFIER_ROLE"
      | "addCandidate"
      | "candidateCount"
      | "closeVoting"
      | "constituencyMeta"
      | "createConstituency"
      | "getCandidate"
      | "getRoleAdmin"
      | "grantRole"
      | "hasRole"
      | "hasVoted"
      | "idFromString"
      | "isVerifiedVoter"
      | "openVoting"
      | "pause"
      | "paused"
      | "regionKey"
      | "renounceRole"
      | "revokeRole"
      | "setCandidateActive"
      | "setVerifiedVoter"
      | "setVerifiedVoters"
      | "supportsInterface"
      | "unpause"
      | "vote"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CandidateAdded"
      | "CandidateStatusChanged"
      | "ConstituencyCreated"
      | "Paused"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "Unpaused"
      | "VoteCast"
      | "VoterVerified"
      | "VotingClosed"
      | "VotingOpened"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "CANDIDATE_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "VERIFIER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addCandidate",
    values: [BytesLike, BytesLike, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "candidateCount",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "closeVoting",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "constituencyMeta",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createConstituency",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getCandidate",
    values: [BytesLike, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasVoted",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "idFromString",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "isVerifiedVoter",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "openVoting",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "regionKey",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setCandidateActive",
    values: [BytesLike, BytesLike, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setVerifiedVoter",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setVerifiedVoters",
    values: [AddressLike[], boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "vote",
    values: [BytesLike, BytesLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "CANDIDATE_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "VERIFIER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addCandidate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "candidateCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "closeVoting",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "constituencyMeta",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createConstituency",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCandidate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasVoted", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "idFromString",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isVerifiedVoter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "openVoting", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "regionKey", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setCandidateActive",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setVerifiedVoter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setVerifiedVoters",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "vote", data: BytesLike): Result;
}

export namespace CandidateAddedEvent {
  export type InputTuple = [
    regionKey: BytesLike,
    candidateId: BigNumberish,
    name: string,
    party: string
  ];
  export type OutputTuple = [
    regionKey: string,
    candidateId: bigint,
    name: string,
    party: string
  ];
  export interface OutputObject {
    regionKey: string;
    candidateId: bigint;
    name: string;
    party: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CandidateStatusChangedEvent {
  export type InputTuple = [
    regionKey: BytesLike,
    candidateId: BigNumberish,
    active: boolean
  ];
  export type OutputTuple = [
    regionKey: string,
    candidateId: bigint,
    active: boolean
  ];
  export interface OutputObject {
    regionKey: string;
    candidateId: bigint;
    active: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ConstituencyCreatedEvent {
  export type InputTuple = [
    regionKey: BytesLike,
    stateId: BytesLike,
    constituencyId: BytesLike
  ];
  export type OutputTuple = [
    regionKey: string,
    stateId: string,
    constituencyId: string
  ];
  export interface OutputObject {
    regionKey: string;
    stateId: string;
    constituencyId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VoteCastEvent {
  export type InputTuple = [
    regionKey: BytesLike,
    voter: AddressLike,
    candidateId: BigNumberish
  ];
  export type OutputTuple = [
    regionKey: string,
    voter: string,
    candidateId: bigint
  ];
  export interface OutputObject {
    regionKey: string;
    voter: string;
    candidateId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VoterVerifiedEvent {
  export type InputTuple = [voter: AddressLike, verified: boolean];
  export type OutputTuple = [voter: string, verified: boolean];
  export interface OutputObject {
    voter: string;
    verified: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VotingClosedEvent {
  export type InputTuple = [regionKey: BytesLike];
  export type OutputTuple = [regionKey: string];
  export interface OutputObject {
    regionKey: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VotingOpenedEvent {
  export type InputTuple = [regionKey: BytesLike];
  export type OutputTuple = [regionKey: string];
  export interface OutputObject {
    regionKey: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface VoteGuardNational extends BaseContract {
  connect(runner?: ContractRunner | null): VoteGuardNational;
  waitForDeployment(): Promise<this>;

  interface: VoteGuardNationalInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  CANDIDATE_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  VERIFIER_ROLE: TypedContractMethod<[], [string], "view">;

  addCandidate: TypedContractMethod<
    [
      stateId: BytesLike,
      constituencyId: BytesLike,
      name: string,
      party: string
    ],
    [void],
    "nonpayable"
  >;

  candidateCount: TypedContractMethod<[arg0: BytesLike], [bigint], "view">;

  closeVoting: TypedContractMethod<
    [stateId: BytesLike, constituencyId: BytesLike],
    [void],
    "nonpayable"
  >;

  constituencyMeta: TypedContractMethod<
    [arg0: BytesLike],
    [
      [boolean, boolean, bigint, bigint, bigint] & {
        created: boolean;
        votingOpen: boolean;
        createdAt: bigint;
        votingOpenedAt: bigint;
        votingClosedAt: bigint;
      }
    ],
    "view"
  >;

  createConstituency: TypedContractMethod<
    [stateId: BytesLike, constituencyId: BytesLike],
    [void],
    "nonpayable"
  >;

  getCandidate: TypedContractMethod<
    [stateId: BytesLike, constituencyId: BytesLike, candidateId: BigNumberish],
    [VoteGuardNational.CandidateStructOutput],
    "view"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  hasVoted: TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [boolean],
    "view"
  >;

  idFromString: TypedContractMethod<[value: string], [string], "view">;

  isVerifiedVoter: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  openVoting: TypedContractMethod<
    [stateId: BytesLike, constituencyId: BytesLike],
    [void],
    "nonpayable"
  >;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  regionKey: TypedContractMethod<
    [stateId: BytesLike, constituencyId: BytesLike],
    [string],
    "view"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  setCandidateActive: TypedContractMethod<
    [
      stateId: BytesLike,
      constituencyId: BytesLike,
      candidateId: BigNumberish,
      active: boolean
    ],
    [void],
    "nonpayable"
  >;

  setVerifiedVoter: TypedContractMethod<
    [voter: AddressLike, verified: boolean],
    [void],
    "nonpayable"
  >;

  setVerifiedVoters: TypedContractMethod<
    [voters: AddressLike[], verified: boolean],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  vote: TypedContractMethod<
    [stateId: BytesLike, constituencyId: BytesLike, candidateId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "CANDIDATE_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "VERIFIER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "addCandidate"
  ): TypedContractMethod<
    [
      stateId: BytesLike,
      constituencyId: BytesLike,
      name: string,
      party: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "candidateCount"
  ): TypedContractMethod<[arg0: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "closeVoting"
  ): TypedContractMethod<
    [stateId: BytesLike, constituencyId: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "constituencyMeta"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [boolean, boolean, bigint, bigint, bigint] & {
        created: boolean;
        votingOpen: boolean;
        createdAt: bigint;
        votingOpenedAt: bigint;
        votingClosedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "createConstituency"
  ): TypedContractMethod<
    [stateId: BytesLike, constituencyId: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getCandidate"
  ): TypedContractMethod<
    [stateId: BytesLike, constituencyId: BytesLike, candidateId: BigNumberish],
    [VoteGuardNational.CandidateStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasVoted"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "idFromString"
  ): TypedContractMethod<[value: string], [string], "view">;
  getFunction(
    nameOrSignature: "isVerifiedVoter"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "openVoting"
  ): TypedContractMethod<
    [stateId: BytesLike, constituencyId: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "regionKey"
  ): TypedContractMethod<
    [stateId: BytesLike, constituencyId: BytesLike],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setCandidateActive"
  ): TypedContractMethod<
    [
      stateId: BytesLike,
      constituencyId: BytesLike,
      candidateId: BigNumberish,
      active: boolean
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setVerifiedVoter"
  ): TypedContractMethod<
    [voter: AddressLike, verified: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setVerifiedVoters"
  ): TypedContractMethod<
    [voters: AddressLike[], verified: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "vote"
  ): TypedContractMethod<
    [stateId: BytesLike, constituencyId: BytesLike, candidateId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "CandidateAdded"
  ): TypedContractEvent<
    CandidateAddedEvent.InputTuple,
    CandidateAddedEvent.OutputTuple,
    CandidateAddedEvent.OutputObject
  >;
  getEvent(
    key: "CandidateStatusChanged"
  ): TypedContractEvent<
    CandidateStatusChangedEvent.InputTuple,
    CandidateStatusChangedEvent.OutputTuple,
    CandidateStatusChangedEvent.OutputObject
  >;
  getEvent(
    key: "ConstituencyCreated"
  ): TypedContractEvent<
    ConstituencyCreatedEvent.InputTuple,
    ConstituencyCreatedEvent.OutputTuple,
    ConstituencyCreatedEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;
  getEvent(
    key: "VoteCast"
  ): TypedContractEvent<
    VoteCastEvent.InputTuple,
    VoteCastEvent.OutputTuple,
    VoteCastEvent.OutputObject
  >;
  getEvent(
    key: "VoterVerified"
  ): TypedContractEvent<
    VoterVerifiedEvent.InputTuple,
    VoterVerifiedEvent.OutputTuple,
    VoterVerifiedEvent.OutputObject
  >;
  getEvent(
    key: "VotingClosed"
  ): TypedContractEvent<
    VotingClosedEvent.InputTuple,
    VotingClosedEvent.OutputTuple,
    VotingClosedEvent.OutputObject
  >;
  getEvent(
    key: "VotingOpened"
  ): TypedContractEvent<
    VotingOpenedEvent.InputTuple,
    VotingOpenedEvent.OutputTuple,
    VotingOpenedEvent.OutputObject
  >;

  filters: {
    "CandidateAdded(bytes32,uint256,string,string)": TypedContractEvent<
      CandidateAddedEvent.InputTuple,
      CandidateAddedEvent.OutputTuple,
      CandidateAddedEvent.OutputObject
    >;
    CandidateAdded: TypedContractEvent<
      CandidateAddedEvent.InputTuple,
      CandidateAddedEvent.OutputTuple,
      CandidateAddedEvent.OutputObject
    >;

    "CandidateStatusChanged(bytes32,uint256,bool)": TypedContractEvent<
      CandidateStatusChangedEvent.InputTuple,
      CandidateStatusChangedEvent.OutputTuple,
      CandidateStatusChangedEvent.OutputObject
    >;
    CandidateStatusChanged: TypedContractEvent<
      CandidateStatusChangedEvent.InputTuple,
      CandidateStatusChangedEvent.OutputTuple,
      CandidateStatusChangedEvent.OutputObject
    >;

    "ConstituencyCreated(bytes32,bytes32,bytes32)": TypedContractEvent<
      ConstituencyCreatedEvent.InputTuple,
      ConstituencyCreatedEvent.OutputTuple,
      ConstituencyCreatedEvent.OutputObject
    >;
    ConstituencyCreated: TypedContractEvent<
      ConstituencyCreatedEvent.InputTuple,
      ConstituencyCreatedEvent.OutputTuple,
      ConstituencyCreatedEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;

    "VoteCast(bytes32,address,uint256)": TypedContractEvent<
      VoteCastEvent.InputTuple,
      VoteCastEvent.OutputTuple,
      VoteCastEvent.OutputObject
    >;
    VoteCast: TypedContractEvent<
      VoteCastEvent.InputTuple,
      VoteCastEvent.OutputTuple,
      VoteCastEvent.OutputObject
    >;

    "VoterVerified(address,bool)": TypedContractEvent<
      VoterVerifiedEvent.InputTuple,
      VoterVerifiedEvent.OutputTuple,
      VoterVerifiedEvent.OutputObject
    >;
    VoterVerified: TypedContractEvent<
      VoterVerifiedEvent.InputTuple,
      VoterVerifiedEvent.OutputTuple,
      VoterVerifiedEvent.OutputObject
    >;

    "VotingClosed(bytes32)": TypedContractEvent<
      VotingClosedEvent.InputTuple,
      VotingClosedEvent.OutputTuple,
      VotingClosedEvent.OutputObject
    >;
    VotingClosed: TypedContractEvent<
      VotingClosedEvent.InputTuple,
      VotingClosedEvent.OutputTuple,
      VotingClosedEvent.OutputObject
    >;

    "VotingOpened(bytes32)": TypedContractEvent<
      VotingOpenedEvent.InputTuple,
      VotingOpenedEvent.OutputTuple,
      VotingOpenedEvent.OutputObject
    >;
    VotingOpened: TypedContractEvent<
      VotingOpenedEvent.InputTuple,
      VotingOpenedEvent.OutputTuple,
      VotingOpenedEvent.OutputObject
    >;
  };
}
